### ISSUE TITLE
IPykernel warning on every display?

### ISSUE THREAD

**Issue by matthew-brett** [buckaroo-data/buckaroo#62] opened 2023-10-19 22:11 UTC
Hi - me again!

I am just testing the latest version - and I notice that:

```python
import buckaroo
import pandas as pd

df = pd.DataFrame(
    dict(names=['one', 'two', 'three'],
         values=[1, 2, 3]))
df
```

gives:

```
/Users/mb312/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
```

Is this what you expected?

I have:

```
$ pip list | grep ipy
ipykernel                 5.3.4
ipython                   8.8.0
ipython-genutils          0.2.0
ipywidgets                8.0.2
```

on Python 3.9 (I know, I'll upgrade soon).

**Comment by paddymul** [comment] 2023-10-21 15:20
I'm not sure.  can you try running
```
import buckaroo
buckaroo.debug_packages()
```

that will list all of the packages and their paths.

I wasn't able to reproduce your bug with the following package list

```
Selected Jupyter core packages...
buckaroo         : 0.3.25
jupyterlab       : 3.6.4
notebook         : 6.5.6
ipywidgets       : 8.0.2
traitlets        : 5.11.2
jupyter_core     : 5.4.0
pandas           : 2.1.1
numpy            : 1.26.0
IPython          : 8.8.0
ipykernel        : 5.3.4
jupyter_client   : 7.4.9
jupyter_server   : 2.8.0
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
qtconsole        : not installed
buckaroo         : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/buckaroo/__init__.py
jupyterlab       : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/jupyterlab/__init__.py
notebook         : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/notebook/__init__.py
ipywidgets       : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/ipywidgets/__init__.py
traitlets        : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/traitlets/__init__.py
jupyter_core     : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/jupyter_core/__init__.py
pandas           : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/pandas/__init__.py
numpy            : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/numpy/__init__.py
IPython          : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/IPython/__init__.py
ipykernel        : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/ipykernel/__init__.py
jupyter_client   : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/jupyter_client/__init__.py
jupyter_server   : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/jupyter_server/__init__.py
nbclient         : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/nbclient/__init__.py
nbconvert        : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/nbconvert/__init__.py
nbformat         : /Users/paddy/anaconda3/envs/buckaroo-install-jp4-3/lib/python3.11/site-packages/nbformat/__init__.py
qtconsole        : not installed
```
however executing `debug_packages()` did cause a similar bug

<img width="767" alt="Screen Shot 2023-10-21 at 11 16 25 AM" src="https://github.com/paddymul/buckaroo/assets/40453/4be41d00-f081-48fb-abf2-ac6daf376268">

Which leads me to believe it's a core jupyterlab/ipywidgets incompatibility.

Are you using conda or regular pip?  I would recommend creating a new environment.

Please do run `buckaroo.debug_widgets()` and report the results.  This will help future users

**Comment by paddymul** [comment] 2023-11-16 19:03
@matthew-brett  I think this is fixed with 0.4.6, can you check on your system

**Comment by paddymul** [comment] 2023-12-18 21:01
I'm closing this because I can't reproduce it and I haven't heard any word from @matthew-brett

**Closed as completed by paddymul** 2023-12-18 21:01 UTC
Labels: bug

**Comment by matthew-brett** [comment] 2023-12-19 14:19
Sorry - term-time intervened.   Installing latest in a virtualenv does not reproduce my original problem - so yes - likely solved - thanks.
